server:
  port: 8080

spring:
  profiles:
    active: dev

  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # [1] 인증 서버
        - id: auth
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/**

        # [2] 메인 API 서버
        - id: api
          uri: ${API_SERVER_URL:http://localhost:8081}
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

      default-filters:
          # ⭐️ 수정 1. RETAIN_UNIQUE를 맨 끝에 추가 (중복 헤더 발생 시 하나만 남김)
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              # ⭐️ 수정 2. 기존 로컬호스트 하드코딩을 지우고 환경변수 문법으로 변경
              - "${FRONTEND_URL:http://localhost:3000}"

            # 2. 메서드는 리스트로 분리 (문자열 X)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

            allowedHeaders: "*"
            allowCredentials: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0